### PR TITLE
fix: Escape odd numbers of single quotes in launch commands on Linux

### LINKED ISSUE #159: Linux - Single apostrophe not escaped in Bash
**Describe the bug**
When launching a game with one single quote (apostrophe) in the launch command, launching fails because there was no closing quote.

**To Reproduce**
1. On Linux, attempt to launch any game with one single quote in the launch command (Luigi's Mansion Interactive is one example, Dusty's Castle is another.)
2. Observe in the logs:

```
INFO  [20:32:40]      Dusty's Castle: Dusty's Castle has been started
INFO  [20:32:40]       Game Launcher: Launch Game "Dusty's Castle" (PID: 3442472) [
                                    applicationPath: "FPSoftware\Flash\flashplayer_32_sa.exe",
                                    launchCommand:   "http://newgrounds.com/Dusty's Castle/585032_dusty_s_castle.swf",
                                    command:         "wine start /unix "/home/jacob/Downloads/flashpoint/custom/FPSoftware/Flash/flashplayer_32_sa.exe" http://newgrounds.com/Dusty's Castle/585032_dusty_s_castle.swf" ]
INFO  [20:32:40]      Dusty's Castle: /bin/sh: -c: line 0: unexpected EOF while looking for matching `''
INFO  [20:32:40]                      /bin/sh: -c: line 1: syntax error: unexpected end of file
INFO  [20:32:40]                      Dusty's Castle exited with code 1
```

**Expected behavior**
A single apostrophe should be escaped for commands running on Linux.

**Screenshots**
N/A (logs should be sufficient.)

**Desktop (please complete the following information):**
 - OS: Arch Linux (kernel 5.4.79-1-lts)
 - Flashpoint Version: both 8.1 and 9.0.
 - Log text: see above.

**Additional context**
- I would normally place a backslash in front of the single-quote to escape it, but this doesn't work, because the backslash _is_ escaped with a second backslash.
- Placing the launch command (or section of the launch command) in double quotes is a functioning workaround.
- It looks like the single quote needs to be added to this line to be escaped: https://github.com/FlashpointProject/launcher/blob/090c415aafb1d2836662627cd97e567cc65869d9/src/back/GameLauncher.ts#L400 
  - However, we can't just escape all single quotes, because some launch commands use pairs of single quotes in a valid way (and would likely be broken by escaping them.)

### PR DESCRIPTION
**Pull request by jacobgkau**
Fixes #159.

As explained in #159, launching certain games currently fails on Linux because single quotes (apostrophes) are not escaped; however, some games also use single quote pairs that should not be escaped. Searching through the current catalog, there are 542 titles with one or more `'` in their launch command:

- 248 titles currently have a single `'` in their launch command (244 Flash and 4 HTML5).
- 294 currently have two or more `'` in their launch command (250 Shockwave and 44 Flash).
  - All of these have an even number of `'` (there are no three, five, seven, etc. occurrences.)

Roughly speaking, the Shockwave titles use single quotes that should not be escaped, while Flash and HTML5 titles use apostrophes in URLs that should be escaped. This PR would not fix the 44 Flash titles that use even numbers of apostrophes, but it would fix the 248 that only have a single apostrophe, without affecting the 250 that are using single quote pairs correctly.

(I wrote the PR before I saw that there are no higher odd numbers in play, but it wouldn't change much to only escape if there's a single apostrophe. It stands to reason that if there's an odd number, it means something wouldn't be closed, so either they all need to be escaped, or the command needs to be revised.)

### CODE REVIEW

**Comment by jacobgkau** [comment]
I'm no JavaScript/TypeScript expert, but I've fixed all of the lint warnings that seemed valid. The backslash and closing square bracket need to be double-escaped to survive the conversion into a regex, and the short-circuit `or` operator prevents the first `if` statement from checking the length of a null string (when there are no apostrophes/single quotes present.)

File: src/back/GameLauncher.ts [hunk 1]
```diff
@@ -394,13 +394,30 @@ function escapeWin(str: string): string {
...
-  return (
-    splitQuotes(str)
-    .reduce((acc, val, i) => acc + ((i % 2 === 0)
-      ? val.replace(/[~`#$&*()\\|[\]{};<>?!]/g, '\\$&')
-      : '"' + val.replace(/[$!\\]/g, '\\$&') + '"'
-    ), '')
-  );
+  // Characters to always escape:
+  const escapeChars: string[] = ['~','`','#','$','&','*','(',')','\\\\','|','[','\\]','{','}',';','<','>','?','!'];
+  if (str.match(/\'/gi) == null || (str.match(/\'/gi)!.join('').length) % 2 == 0) {
```
Comment (colin969) [inline src/back/GameLauncher.ts:399]: You're getting a non-null assertion because you're comparing 2 (potentionally) different results. Set it to a variable first.

```
  const match = str.match(/'/gi);
  if (match == null || match.join('').length % 2 == 0) {
  ...
```

The escapes inside your regexes should be fine to remove, both /'/gi and /\'/gi will match the same.

**Review by colin969 — CHANGES_REQUESTED** [review]

File: src/back/GameLauncher.ts (hunk 1 above)
Comment (jacobgkau) [reply src/back/GameLauncher.ts]: Understood on the non-null assertion, I've added the variable.

For the escapes, I've confirmed that if I remove even one of the two backslashes currently before the closing square bracket, affected games will not start. It needs two backslashes in the way it's currently written. There aren't actually any games in the database that have a backslash in their launch command, but testing here, it looks like double-escaping is necessary for the backslash-escape as well: [TS Playground](https://www.typescriptlang.org/play?#code/DYUwLgBCDODGCGAHEBhAFvATtAXBaYmAlgHYDmA2gLoQC8EFA5AH6MA0jABu4wMQ8ASHgDIeAKh4AKHgEoeAHXk8APjyYd5VHgG8eAXx4BuHgB4eAPh4B+HgEJ2ERksZVDAKFgB7EtE+gAdMCeZJIwCMjoWND+AFaepJIARIkyMu4AblgQALYAngBqWETwAEagdI4A4vDZIErQEF7Z2fAkACYQZJ4wEIoQaCCYIFT+jB7evgFBIXmFxKWgMuM+fiCBwZKzRQtrQ4jA8LAgkiQgAO4QAEogZACiAB6ISRSJEADUUHBIqBjYsfEkJIpd4QRJURJsRxkRgySFOeQCUSpNzLSZrabSGHuNxhb6RbAVJisDjcDj8DhCDiiDgSDjSDhyDSKJQcVQcdTwrQcXQcAwcYwcMwcSwcGwcexw5yuVGrdYhXERX7ROIJZKpDJZLbzMogCqMaq1eqNTzNVodLo9PoDIYjMZeFZTDZa4o6pb2tFyzYFbY6-x7A5HE7nK43B5PRIvEEKn5Rf6q4EfMEQqEwyUIpEyIA)

I think what's happening is that the first escape is "used" when creating the array, and the second one is "used" when creating the RegExp object (where it's actually needed.) If you'd prefer, I could just put the "hard-coded" string back into the `val.replace` function (with a `'` in the second case and no `'` in the first case.) I just thought it would be more elegant to not duplicate that list of characters, since it's only a single-character difference. (I just now remembered that part of the point was to only need the `reduce` function there once, so I've gotten rid of the duplicate to further clean it up in the latest commit.)
